"use client";
import { useCallback, useEffect, useState } from "react";
import { api, pct } from "@/lib/api";
import { useLiveRefresh } from "@/lib/live";
import { ErrorBox, Loading } from "@/components/Loading";
function age(seconds:any){if(seconds===null||seconds===undefined)return "—";const s=Number(seconds);if(s<60)return `${Math.round(s)}s`;if(s<3600)return `${Math.round(s/60)}m`;return `${(s/3600).toFixed(1)}h`;}
function statusClass(s:string){const u=(s||"").toUpperCase();return u==="HEALTHY"?"positive":u.includes("DISABLED")||u.includes("NO_CREDENTIALS")||u.includes("RESEARCH")?"muted":u.includes("NO_QUOTA")||u.includes("STALE")?"negative":""}
export default function SystemPage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState("");const load=useCallback(async()=>{try{setData(await api<any>("/system"));setError("")}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{load()},[load]);useLiveRefresh(load);
 if(error&&!data)return <ErrorBox error={error}/>;if(!data)return <Loading/>;
 return <><header className="pageHead"><div><h1>Models / system</h1><p>Operational health, data provenance and provider budgets. HTTP 200 alone is not treated as healthy data.</p></div></header><div className="stack">
 <section className="panel"><div className="panelTitle"><h2>Collectors</h2></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Collector</th><th>Status</th><th>Last run</th><th>Written</th><th>Error</th></tr></thead><tbody>{data.collectors.map((x:any)=><tr key={x.collector}><td>{x.collector}</td><td>{x.status}</td><td>{x.started_at?new Date(x.started_at).toLocaleString():"—"}</td><td>{x.records_written}</td><td>{x.error||"—"}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panelTitle"><h2>Providers</h2><span className="muted">Each provider is optional</span></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Provider</th><th>Role / access</th><th>Enabled</th><th>Markets</th><th>Status</th><th>Last success / failure</th><th>Age / latency</th><th>Requests / errors</th><th>Seen / ingested / dupes</th><th>Quarantine</th><th>Rate left</th><th>Gap</th></tr></thead><tbody>{data.providers.map((x:any,i:number)=><tr key={i}><td><strong>{x.provider}</strong><span className="sourceMeta">certainty {pct(x.platform_certainty)}</span></td><td>{x.role}<span className="sourceMeta">{x.access_type||"—"}</span></td><td>{x.enabled===false?"no":"yes"}</td><td>{(x.market_segments_supported||[]).join(", ")||x.market||"—"}</td><td className={statusClass(x.status)}><strong>{x.status||"—"}</strong></td><td>{x.last_success_at?new Date(x.last_success_at).toLocaleString():"—"}<span className="sourceMeta">fail {x.last_failure_at?new Date(x.last_failure_at).toLocaleString():"—"}</span></td><td>{age(x.latest_observation_age_seconds)}<span className="sourceMeta">{x.last_latency_ms!=null?`${Math.round(x.last_latency_ms)}ms`:"—"}</span></td><td>{x.requests??0} / {x.errors??0}<span className="sourceMeta">{pct(x.error_rate)}</span></td><td>{x.items_seen??0} / {x.items_ingested??0} / {x.duplicates_skipped??0}</td><td>{x.quarantined_observations??0}<span className="sourceMeta">parse {x.parsing_failures??0} · norm {x.normalization_failures??0} · id {x.identity_failures??0}</span></td><td>{x.rate_limit_remaining??"—"}</td><td>{x.gap_status||"—"}</td></tr>)}</tbody></table></div></section>
 {data.provider_budgets?.length>0&&<section className="panel"><div className="panelTitle"><h2>Provider budgets</h2></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Provider</th><th>Mode</th><th>Requests</th><th>Remaining</th><th>Credits</th><th>Daily estimate</th><th>Monthly estimate</th></tr></thead><tbody>{data.provider_budgets.map((x:any,i:number)=><tr key={i}><td>{x.provider}</td><td>{x.access_mode}</td><td>{x.requests_used}</td><td>{x.requests_remaining??"—"}</td><td>{x.credits_used??0}</td><td>{x.estimated_daily_cost??"—"}</td><td>{x.estimated_monthly_cost??"—"}</td></tr>)}</tbody></table></div></section>}
 <section className="panel"><div className="panelTitle"><h2>Models / workers</h2></div>{data.models.length===0&&data.heartbeats.length===0?<p className="muted">No model runs or GPU worker heartbeat yet. Live collection and the app do not depend on the RTX 5080 worker.</p>:null}{data.models.map((x:any,i:number)=><div className="activityItem" key={i}><div></div><div><strong>{x.model} · {x.version}</strong><p>{x.status} · {x.finished_at?new Date(x.finished_at).toLocaleString():"running"}</p></div></div>)}{data.heartbeats.map((x:any,i:number)=><div className="activityItem" key={`h-${i}`}><div></div><div><strong>{x.service} · {x.node}</strong><p>{x.status} · {new Date(x.last_seen_at).toLocaleString()}</p></div></div>)}</section>
 {data.incidents.length>0&&<section className="panel"><div className="panelTitle"><h2>Open data-quality incidents</h2></div>{data.incidents.map((x:any,i:number)=><div className="activityItem" key={i}><div></div><div><strong>{x.severity.toUpperCase()} · {x.type}</strong><p>{x.description}</p></div></div>)}</section>}
 </div></>;
}
