"use client";
import { useCallback, useEffect, useState } from "react";
import { api, age, coins, pct } from "@/lib/api";
import { VerificationRequest } from "@/lib/types";
import { useLiveRefresh } from "@/lib/live";
import { ErrorBox, Loading } from "@/components/Loading";

function VerificationForm({request,onDone}:{request:VerificationRequest;onDone:()=>void}){
 const [prices,setPrices]=useState("");const [approx,setApprox]=useState(false);const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState(false);const [result,setResult]=useState<any>(null);const [error,setError]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const fd=new FormData();fd.append("observed_at",new Date().toISOString());fd.append("listing_prices",prices);fd.append("approximate",String(approx));if(file)fd.append("screenshot",file);const r=await api<any>(`/manual-verifications/${request.id}/evidence`,{method:"POST",body:fd});setResult(r);if(r.resolved)setTimeout(onDone,800)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <form className="form" onSubmit={submit}><div className="field"><label>Lowest 5–10 PC BIN listings</label><textarea placeholder="95000, 95500, 96000, 96500, 97000" value={prices} onChange={e=>setPrices(e.target.value)}/></div><div className="field"><label>Screenshot (optional but raises confidence when paired with exact prices)</label><input type="file" accept="image/png,image/jpeg,image/webp" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><label className="muted"><input style={{width:"auto",marginRight:8}} type="checkbox" checked={approx} onChange={e=>setApprox(e.target.checked)}/>Values are approximate</label>{error&&<div className="dangerNotice">{error}</div>}{result&&<div className="notice">Result: <strong>{result.action}</strong> · execution-observation confidence {pct(result.execution_observation_confidence ?? result.observation_confidence)}{result.trade_model_confidence!==null&&result.trade_model_confidence!==undefined?` · trade/model confidence ${pct(result.trade_model_confidence)}`:""}{result.lowest_bin?` · lowest ${coins(result.lowest_bin)}`:""}</div>}<button className="button" disabled={busy||(!prices.trim()&&!file)}>{busy?"Saving…":"Submit market check"}</button></form>;
}

export default function VerifyPage(){
 const [rows,setRows]=useState<VerificationRequest[]|null>(null);const [error,setError]=useState("");const load=useCallback(async()=>{try{setRows(await api<VerificationRequest[]>("/manual-verifications/pending"));setError("")}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{load()},[load]);useLiveRefresh(load);
 return <><header className="pageHead"><div><h1>Verify</h1><p>Only interrupt when fresh execution information can change the trade decision.</p></div></header>{error&&<ErrorBox error={error}/>} {!rows?<Loading/>:<div className="stack">{rows.length?rows.map(r=><section className="panel verifyCard" key={r.id}><div className="pageHead" style={{marginBottom:14}}><div><h1 style={{fontSize:18}}>VERIFY — {r.card}</h1><p>{r.card_version} · priority {r.priority}/10</p></div></div><div className="verifyGrid"><div><div className="kv"><span>Reference</span><strong>{coins(r.latest_reference_price)}</strong></div><div className="kv"><span>Reference age</span><strong>{age(r.reference_age_seconds)}</strong></div><div className="kv"><span>Attractive ≤</span><strong>{coins(r.attractive_at_or_below)}</strong></div><div className="kv"><span>Expected range</span><strong>{coins(r.expected_acquisition_range?.[0])}–{coins(r.expected_acquisition_range?.[1])}</strong></div><div className="kv"><span>Uncertainty</span><strong>{pct(r.reference_uncertainty_pct)}</strong></div><p className="muted">{r.reason}</p><p><strong>Need:</strong> {r.required_information}</p></div><VerificationForm request={r} onDone={load}/></div></section>):<section className="panel"><strong>No verification requests.</strong><p className="muted">The system won’t ask you to check cards unless the expected information value justifies the interruption.</p></section>}</div>}</>;
}
