"use client";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, coins, duration, pct } from "@/lib/api";
import { ErrorBox, Loading } from "@/components/Loading";

export default function StrategyDetail(){
 const {slug}=useParams<{slug:string}>(); const [x,setX]=useState<any>(null); const [error,setError]=useState("");
 useEffect(()=>{api<any>(`/strategies/${slug}`).then(setX).catch(e=>setError((e as Error).message))},[slug]);
 if(error&&!x)return <ErrorBox error={error}/>; if(!x)return <Loading/>;
 return <><header className="pageHead"><div><h1>{x.name}</h1><p>{x.evidence_class} · {x.viability_status} · measured n={x.sample_size||0}</p></div></header>
 <div className="grid2"><div className="stack"><section className="panel"><div className="panelTitle"><h2>Mechanism</h2></div><p>{x.explanation}</p><p className="muted">{x.mechanism}</p><div className="tabs">{(x.card_categories||[]).map((v:string)=><span className="pill" key={v}>{v}</span>)}{(x.market_regimes||[]).map((v:string)=><span className="pill" key={v}>{v}</span>)}</div></section>
 <section className="panel"><div className="panelTitle"><h2>Measured performance</h2></div>{x.performance_history?.length?<div className="detailGrid"><div className="detailCard"><small>Sample</small><strong>{x.performance_history[0].sample_size}</strong></div><div className="detailCard"><small>Net Transfer Profit</small><strong>{coins(x.performance_history[0].total_net_transfer_profit)}</strong></div><div className="detailCard"><small>Hit rate</small><strong>{pct(x.performance_history[0].hit_rate)}</strong></div><div className="detailCard"><small>ROI</small><strong>{pct(x.performance_history[0].roi)}</strong></div><div className="detailCard"><small>Profit/hour</small><strong>{coins(x.performance_history[0].profit_per_hour)}</strong></div><div className="detailCard"><small>Acquisition probability</small><strong>{pct(x.performance_history[0].acquisition_probability)}</strong></div></div>:<p className="muted">Not measured yet. Source evidence is not being presented as backtest performance.</p>}</section>
 <section className="panel"><div className="panelTitle"><h2>Source evidence</h2><span className="muted">{x.evidence?.length||0} records</span></div>{(x.evidence||[]).map((e:any,i:number)=><div className="activityItem" key={i}><div></div><div><strong>{e.cycle} · {e.title||e.source_kind}</strong><p>{e.author||"unknown author"} · {e.direction} · quality {pct(e.quality_score)}<br/>{e.notes||""}</p></div></div>)}</section></div>
 <div className="stack"><section className="panel"><div className="panelTitle"><h2>Temporal validity</h2></div>{(x.cycle_assessments||[]).map((c:any,i:number)=><div className="activityItem" key={i}><div></div><div><strong>{c.cycle} · decay {pct(c.decay_risk)}</strong><p>{c.reason||c.viability_status}</p></div></div>)||null}</section><section className="panel"><div className="panelTitle"><h2>Trader specialists</h2></div>{x.trader_specialists?.length?x.trader_specialists.map((t:any)=><div className="activityItem" key={t.handle}><div></div><div><strong>{t.handle} · {pct(t.reputation_score)}</strong><p>n={t.sample_size} · after-tax profitable {pct(t.profitable_after_tax_rate)} · alpha {pct(t.average_alpha_pct)}</p></div></div>):<p className="muted">No resolved strategy-specific trader sample yet.</p>}</section><section className="panel"><div className="panelTitle"><h2>Failure / exit logic</h2></div><p><strong>Exit:</strong> {x.exit_logic||"Not yet formalized beyond live model exit logic."}</p><p><strong>Invalidation:</strong> {x.invalidation_conditions||"Measured failures will populate this as FC26 evidence accumulates."}</p><p><strong>EA intervention:</strong> {x.ea_intervention_risk||"—"}</p></section></div></div></>;
}
