"use client";
import { useMemo, useState } from "react";
import { api, coins, pct } from "@/lib/api";
import { Sparkline } from "@/components/Sparkline";
import { ActionBadge } from "@/components/ActionBadge";
import { ErrorBox } from "@/components/Loading";
function age(s:any){if(s===null||s===undefined)return "—";const n=Number(s);if(n<60)return `${Math.round(n)}s`;if(n<3600)return `${Math.round(n/60)}m`;return `${(n/3600).toFixed(1)}h`;}
const order=["PC","PLAYSTATION","CONSOLE_GENERIC","CONSOLE_SHARED","SWITCH","UNKNOWN"];
export default function MarketPage(){
 const [q,setQ]=useState("");const [rows,setRows]=useState<any[]>([]);const [data,setData]=useState<any>(null);const [segment,setSegment]=useState("PC");const [error,setError]=useState("");
 async function search(){try{setRows(await api<any[]>(`/market/search?q=${encodeURIComponent(q)}`));setError("")}catch(e){setError((e as Error).message)}}
 async function open(id:string){try{const d=await api<any>(`/market/cards/${id}`);setData(d);setSegment(d.default_market_segment||"PC");setRows([]);setError("")}catch(e){setError((e as Error).message)}}
 const available=useMemo(()=>data?order.filter(k=>data.market_segments?.[k]):[],[data]);
 const current=data?.market_segments?.[segment];
 const refs=(current?.reference_prices||[]);const execs=(current?.execution_observations||[]);const prices=refs.slice().reverse().map((x:any)=>x.price).filter(Boolean);
 const moves=(data?.market_moves||[]).filter((m:any)=>m.market_segment===segment || (segment!=="UNKNOWN"&&m.market_segment==="UNKNOWN"));
 return <><header className="pageHead"><div><h1>FC26 market intelligence</h1><p>PC is your execution market. Other segments are research signals and are never merged into PC execution truth.</p></div></header>
 <section className="panel"><div className="formRow"><input placeholder="Search player/card" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")search()}}/><button className="button" onClick={search}>Search</button></div>{rows.length>0&&<div className="searchResults">{rows.map(r=><button key={r.id} className="searchItem" onClick={()=>open(r.id)}><strong>{r.rating?`${r.rating} `:""}{r.name}</strong> <span className="muted">{r.version||"Base"} · {r.position||""}</span></button>)}</div>}{error&&<ErrorBox error={error}/>}</section>
 {data&&<div className="stack" style={{marginTop:12}}><section className="panel"><div className="pageHead" style={{marginBottom:12}}><div><h1 style={{fontSize:20}}>{data.card.rating?`${data.card.rating} `:""}{data.card.name}</h1><p>{data.card.version||"Unknown version"} · {data.card.position||""} · {data.card.league||""}</p></div>{data.active_opportunity&&<ActionBadge action={data.active_opportunity.action}/>}</div><div className="tabs">{available.map(k=><button key={k} className={`pill ${segment===k?"activePill":""}`} onClick={()=>setSegment(k)}>{data.market_segments[k].display_name||k}{data.market_segments[k].executable_by_user?" · ACTIONABLE":""}</button>)}</div><div className="statusBanner info" style={{marginTop:12}}>{data.reference_warning}</div></section>
 <section className="panel"><div className="panelTitle"><h2>{current?.display_name||segment} reference prices</h2><span className="muted">REFERENCE · not guaranteed executable</span></div><Sparkline values={prices}/><div className="tableWrap"><table className="dataTable"><thead><tr><th>Retrieved</th><th>Provider</th><th>Provider time</th><th>Age</th><th>Price</th><th>Confidence</th><th>Quality</th></tr></thead><tbody>{refs.length?refs.map((x:any)=><tr key={x.id}><td>{x.at?new Date(x.at).toLocaleString():"—"}</td><td>{x.source||"—"}</td><td>{x.provider_at?new Date(x.provider_at).toLocaleString():"—"}</td><td>{age(x.age_seconds)}</td><td>{coins(x.price)}</td><td>{pct(x.confidence)}</td><td>{x.quality_status||"—"}</td></tr>):<tr><td colSpan={7} className="muted">No stored reference observations for this market segment.</td></tr>}</tbody></table></div></section>
 <section className="panel"><div className="panelTitle"><h2>Execution observations</h2><span className="muted">Current/local market evidence</span></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Observed</th><th>Lowest BIN</th><th>Listing ladder</th><th>Confidence</th><th>Type</th><th>Quality</th></tr></thead><tbody>{execs.length?execs.map((x:any)=><tr key={x.id}><td>{x.at?new Date(x.at).toLocaleString():"—"}</td><td>{coins(x.lowest_bin)}</td><td>{(x.listing_prices||[]).map((n:number)=>coins(n)).join(" · ")||"—"}</td><td>{pct(x.confidence)}</td><td>{x.type||"—"}</td><td>{x.quality_status||"—"}</td></tr>):<tr><td colSpan={6} className="muted">No execution observations for this market segment.</td></tr>}</tbody></table></div></section>
 <section className="panel"><div className="panelTitle"><h2>Market moves</h2><span className="muted">EVENT / MARKET CONTEXT</span></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Provider</th><th>Market</th><th>Old</th><th>New</th><th>Move</th><th>Provider time</th><th>Quality</th></tr></thead><tbody>{moves.length?moves.slice(0,100).map((m:any)=><tr key={m.id}><td>{m.provider||"—"}</td><td>{m.market_segment}</td><td>{coins(m.old_price)}</td><td>{coins(m.new_price)}</td><td>{pct(m.percentage_change)}</td><td>{m.provider_timestamp?new Date(m.provider_timestamp).toLocaleString():"—"}</td><td>{m.quality_status||"—"}</td></tr>):<tr><td colSpan={7} className="muted">No matching market-move events. UNKNOWN events remain context only.</td></tr>}</tbody></table></div></section>
 <section className="panel"><div className="panelTitle"><h2>Content & catalysts</h2><span className="muted">EA / provider events linked to this card</span></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Detected</th><th>Source</th><th>Type</th><th>Title</th><th>Impact</th><th>Evidence</th></tr></thead><tbody>{(data.content_events||[]).length?(data.content_events||[]).map((e:any)=><tr key={e.event_id}><td>{e.detected_at?new Date(e.detected_at).toLocaleString():"—"}</td><td>{e.source||"—"}</td><td>{e.event_type||"—"}</td><td>{e.title||"—"}</td><td>{e.direction||e.impact_type||"—"}</td><td>{e.evidence_class||"—"}</td></tr>):<tr><td colSpan={6} className="muted">No card-linked content events yet.</td></tr>}</tbody></table></div></section>
 </div>}
 </>;
}
