PREDICTION_HORIZONS_SECONDS = {
    "5m": 5 * 60,
    "15m": 15 * 60,
    "1h": 60 * 60,
    "3h": 3 * 60 * 60,
    "6h": 6 * 60 * 60,
    "24h": 24 * 60 * 60,
    "3d": 3 * 24 * 60 * 60,
    "7d": 7 * 24 * 60 * 60,
}

PRICE_LAGS_SECONDS = [120, 300, 900, 3600, 10800, 21600, 86400]

BASE_FEATURES = [
    "reference_price",
    "reference_age_seconds",
    "reference_provider_error_pct",
    "reference_stated_uncertainty_pct",
    "reference_uncertainty_pct",
    "reference_confidence",
    "execution_price",
    "execution_age_seconds",
    "reference_execution_gap_pct",
    "acquisition_probability",
    "expected_acquisition_price",
    "expected_acquisition_delay_seconds",
    "current_price",
    "price_change_2m",
    "price_change_5m",
    "price_change_15m",
    "price_change_1h",
    "price_change_3h",
    "price_change_6h",
    "price_change_24h",
    "listing_count_change_5m",
    "listing_count_change_15m",
    "sales_velocity_5m",
    "sales_velocity_15m",
    "spread_abs",
    "spread_pct",
    "market_index_change_15m",
    "category_index_change_15m",
    "comparable_move_15m",
    "hour_sin",
    "hour_cos",
    "day_of_week",
    "seconds_to_content",
    "seconds_to_rewards",
    "sbc_demand_score",
    "evo_eligibility_score",
    "pack_supply_score",
    "out_of_pack",
    "promo_active",
    "substitutability_score",
    "chemistry_graph_degree",
    "ea_intervention_risk",
    "strategy_match_count",
    "strategy_best_similarity",
    "strategy_best_confidence",
    "strategy_weighted_success_rate",
    "strategy_weighted_median_return",
    "strategy_historical_sample_size",
    "strategy_decay_risk",
]
