"use client";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { api, age, coins, duration, pct } from "@/lib/api";
import { ActionBadge } from "@/components/ActionBadge";
import { Sparkline } from "@/components/Sparkline";
import { ErrorBox, Loading } from "@/components/Loading";

export default function OpportunityDetail(){
 const {id}=useParams<{id:string}>(); const [x,setX]=useState<any>(null);const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setX(await api<any>(`/opportunities/${id}`));setError("")}catch(e){setError((e as Error).message)}},[id]); useEffect(()=>{load()},[load]);
 if(error&&!x)return <ErrorBox error={error}/>; if(!x)return <Loading/>;
 const prices=(x.reference_history||[]).map((p:any)=>p.price).filter(Boolean);
 return <><header className="pageHead"><div><h1>{x.rating?`${x.rating} `:""}{x.card}</h1><p>{x.card_version} · Rank #{x.rank||"—"}</p></div><ActionBadge action={x.action}/></header>
 <section className="metrics"><div className="metric"><span>Reference</span><strong>{coins(x.reference_price)}</strong><small>{x.reference_source||"reference"} · {age(x.reference_age_seconds)} old</small></div><div className="metric"><span>Buy ≤</span><strong>{coins(x.max_buy_price)}</strong><small>{x.recommended_quantity||1} recommended</small></div><div className="metric"><span>Sell range</span><strong>{coins(x.target_sell_low)}–{coins(x.target_sell_high)}</strong><small>{duration(x.expected_holding_seconds)}</small></div><div className="metric"><span>Expected net</span><strong>{coins(x.expected_net_profit)}</strong><small>{pct(x.expected_roi)} · {coins(x.expected_profit_per_hour)}/h</small></div></section>
 <div className="grid2"><div className="stack"><section className="panel"><div className="panelTitle"><h2>Reference history</h2><span className="muted">{x.reference_history?.length||0} observations</span></div><Sparkline values={prices}/></section>
 <section className="panel"><div className="panelTitle"><h2>Why this exists</h2></div><div className="detailGrid"><div className="detailCard"><small>Acquisition probability</small><strong>{pct(x.acquisition_probability)}</strong></div><div className="detailCard"><small>Profitable exit</small><strong>{pct(x.profitable_exit_probability)}</strong></div><div className="detailCard"><small>Liquidity</small><strong>{pct(x.liquidity_score)}</strong></div><div className="detailCard"><small>Trade/model confidence</small><strong>{pct(x.trade_model_confidence ?? x.confidence)}</strong></div><div className="detailCard"><small>EA intervention</small><strong>{pct(x.ea_intervention_risk)}</strong></div><div className="detailCard"><small>Latest execution mark</small><strong>{coins(x.latest_execution_price)}</strong><span className="sourceMeta">{x.latest_execution_source||"execution"} · {age(x.latest_execution_age_seconds)} old · observation confidence {pct(x.execution_confidence)}</span></div><div className="detailCard"><small>Model agreement</small><strong>{pct(x.model_agreement)}</strong></div><div className="detailCard"><small>Undercut samples</small><strong>{x.acquisition_summary?.sample_size||0}</strong></div></div><p><strong>Catalyst:</strong> {x.main_catalyst||"No explicit catalyst recorded."}</p><p><strong>Invalidation:</strong> {x.invalidation_condition||"Not yet specified."}</p><p><strong>Exit:</strong> {x.exit_logic||"Not yet specified."}</p></section>
 <section className="panel"><div className="panelTitle"><h2>Cross-market context</h2><span className="muted">research evidence, not execution truth</span></div><div className="detailGrid"><div className="detailCard"><small>PC reference consensus</small><strong>{coins(x.cross_market_context?.pc_price)}</strong></div><div className="detailCard"><small>PlayStation reference</small><strong>{coins(x.cross_market_context?.playstation_price)}</strong></div><div className="detailCard"><small>Generic console reference</small><strong>{coins(x.cross_market_context?.console_generic_price)}</strong></div><div className="detailCard"><small>Switch reference</small><strong>{coins(x.cross_market_context?.switch_price)}</strong></div><div className="detailCard"><small>PC / console ratio</small><strong>{x.cross_market_context?.pc_console_ratio==null?"—":Number(x.cross_market_context.pc_console_ratio).toFixed(3)}</strong></div><div className="detailCard"><small>PC / Switch ratio</small><strong>{x.cross_market_context?.pc_switch_ratio==null?"—":Number(x.cross_market_context.pc_switch_ratio).toFixed(3)}</strong></div></div><p className="muted">Lead/lag and convergence fields remain unclaimed until enough paired real history exists.</p></section>
 <section className="panel"><div className="panelTitle"><h2>Historical strategy match</h2></div>{x.strategy_matches?.length?x.strategy_matches.slice(0,3).map((m:any)=><div className="activityItem" key={m.strategy_id}><div></div><div><strong>Pattern resembles {m.name}</strong><p>{pct(m.similarity)} similarity · {pct(m.confidence)} confidence · {m.historical_sample_size?`measured n=${m.historical_sample_size}`:"not yet backtested"}{m.current_conditions_differ?" · current conditions differ":""}</p></div></div>):<p className="muted">No meaningful historical-strategy match. Current market evidence still drives the opportunity.</p>}</section>
 <section className="panel"><div className="panelTitle"><h2>Acquisition / undercut evidence</h2></div><div className="detailGrid"><div className="detailCard"><small>Samples</small><strong>{x.acquisition_summary?.sample_size||0}</strong></div><div className="detailCard"><small>Mean discount</small><strong>{pct(x.acquisition_summary?.mean_discount_to_reference)}</strong></div><div className="detailCard"><small>Mean wait</small><strong>{duration(x.acquisition_summary?.mean_time_to_opportunity_seconds)}</strong></div></div></section>
 <section className="panel"><div className="panelTitle"><h2>Model forecasts</h2><span className="muted">agreement {pct(x.model_agreement)}</span></div><div className="tableWrap"><table className="dataTable"><thead><tr><th>Model</th><th>Horizon</th><th>Sell</th><th>Net</th><th>Profitable exit</th></tr></thead><tbody>{(x.forecasts||[]).map((f:any,i:number)=><tr key={i}><td>{f.model}</td><td>{duration(f.horizon_seconds)}</td><td>{coins(f.future_sell_price)}</td><td>{coins(f.expected_net_profit)}</td><td>{pct(f.profitable_exit_probability)}</td></tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panelTitle"><h2>Events / analogues / score drivers</h2></div>{x.event_relationships?.length?x.event_relationships.slice(0,8).map((e:any,i:number)=><div className="activityItem" key={i}><div></div><div><strong>{e.impact_type} · {e.direction||"mixed"}</strong><p>{e.reason||"Linked market event"}</p></div></div>):<p className="muted">No linked SBC/Evo/promo reaction stored yet.</p>}<div className="tabs" style={{marginTop:10}}>{Object.entries(x.score_components||{}).sort((a:any,b:any)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,8).map(([k,v]:any)=><span className="pill" key={k}>{k}: {Number(v).toFixed(2)}</span>)}</div>{x.historical_analogues?.length?<p className="muted">Analogues: {x.historical_analogues.map((a:any)=>typeof a==="string"?a:(a.key||JSON.stringify(a))).join(" · ")}</p>:null}</section></div>
 <div className="stack"><section className="panel"><div className="panelTitle"><h2>Execution evidence</h2></div>{(x.execution_observations||[]).slice(0,8).map((e:any,i:number)=><div key={i} className="activityItem"><time>{new Date(e.observed_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time><div><strong>{coins(e.lowest_bin)}</strong><p>Execution-observation confidence {pct(e.confidence)} · {e.listing_prices?.length?`${e.listing_prices.length} listings`:e.type}</p></div></div>)||null}</section><section className="panel"><div className="panelTitle"><h2>Community signals</h2></div>{x.community_signals?.length?x.community_signals.map((s:any)=><div className="activityItem" key={s.signal_id}><div></div><div><strong>{s.direction.toUpperCase()} · {coins(s.quoted_entry)} → {coins(s.target_price)}</strong><p>{s.catalyst||"No catalyst text"}</p></div></div>):<p className="muted">No tracked community call linked to this card yet.</p>}</section></div></div></>;
}
