"use client";
import { useCallback, useEffect, useState } from "react";
import { api, age, coins, pct } from "@/lib/api";
import { ActionBadge } from "@/components/ActionBadge";
import { ErrorBox, Loading } from "@/components/Loading";
import { useLiveRefresh } from "@/lib/live";

function projectedProfit(position:any, raw:string):number|null{
  const price=Number(raw);
  if(!Number.isFinite(price)||price<=0)return null;
  const gross=price*Number(position.quantity||0);
  const tax=Math.floor(gross*0.05);
  return gross-tax-Number(position.capital_deployed||0);
}

export default function PortfolioPage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState("");const [balance,setBalance]=useState("");const [query,setQuery]=useState("");const [cards,setCards]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [qty,setQty]=useState("1");const [price,setPrice]=useState("");const [salePos,setSalePos]=useState<any>(null);const [saleQty,setSaleQty]=useState("");const [salePrice,setSalePrice]=useState("");const [desired,setDesired]=useState<Record<string,string>>({});const [saving,setSaving]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const d=await api<any>("/portfolio");setData(d);setBalance(String(d.account.current_coins||0));setDesired(prev=>{const next={...prev};for(const p of d.positions||[]){if(next[p.position_id]===undefined)next[p.position_id]=p.desired_listing_price?String(p.desired_listing_price):"";}return next});setError("")}catch(e){setError((e as Error).message)}},[]);useEffect(()=>{load()},[load]);useLiveRefresh(load);
 async function saveBalance(){try{await api("/portfolio/balance",{method:"PUT",body:JSON.stringify({coins:Number(balance)})});load()}catch(e){setError((e as Error).message)}}
 async function search(){if(query.trim().length<2)return;setCards(await api<any[]>(`/market/search?q=${encodeURIComponent(query)}`))}
 async function buy(){if(!selected)return;try{await api("/portfolio/purchases",{method:"POST",body:JSON.stringify({card_id:selected.id,quantity:Number(qty),unit_price:Number(price)})});setSelected(null);setPrice("");setQuery("");setCards([]);load()}catch(e){setError((e as Error).message)}}
 function beginSale(p:any){setSalePos(p);setSaleQty(String(p.quantity));setSalePrice(desired[p.position_id]||String(p.current_lowest_bin||""))}
 async function sell(){if(!salePos)return;try{await api("/portfolio/sales",{method:"POST",body:JSON.stringify({card_id:salePos.card_id,quantity:Number(saleQty),unit_price:Number(salePrice)})});setSalePos(null);setSaleQty("");setSalePrice("");load()}catch(e){setError((e as Error).message)}}
 async function saveDesired(p:any){const raw=(desired[p.position_id]||"").trim();const value=raw?Number(raw):null;if(raw&&(!Number.isFinite(value)||Number(value)<=0)){setError("Desired listing price must be a positive number.");return}setSaving(p.position_id);try{await api(`/portfolio/positions/${p.position_id}/desired-listing-price`,{method:"PUT",body:JSON.stringify({desired_listing_price:value})});setError("");await load()}catch(e){setError((e as Error).message)}finally{setSaving(null)}}
 if(!data&&!error)return <Loading/>;
 return <><header className="pageHead"><div><h1>Portfolio</h1><p>Manual EA execution, executable mark-to-market, and exact 5% tax accounting.</p></div></header>{error&&<ErrorBox error={error}/>}<section className="metrics"><div className="metric"><span>Available coins</span><strong>{coins(data?.account.current_coins)}</strong></div><div className="metric"><span>Realized Transfer Profit</span><strong>{coins(data?.account.realized_profit)}</strong></div><div className="metric"><span>EA tax paid</span><strong>{coins(data?.account.ea_tax_paid)}</strong></div><div className="metric"><span>Open positions</span><strong>{data?.positions.length||0}</strong></div></section>
 <div className="grid2"><section className="panel"><div className="panelTitle"><h2>Positions</h2><span className="muted">Reference value is never used as an executable quote</span></div>{data?.positions.length?<div className="tableWrap"><table className="dataTable"><thead><tr><th>Card</th><th>Qty</th><th>Avg buy</th><th>Current lowest BIN / executable mark</th><th>Liquidation P/L after tax</th><th>Reference / fair-value anchor</th><th>Desired listing</th><th>Projected P/L after tax</th><th>Action</th><th></th></tr></thead><tbody>{data.positions.map((p:any)=>{const projected=projectedProfit(p,desired[p.position_id]||"");return <tr key={p.position_id}><td><strong>{p.card}</strong><br/><span className="muted">{p.card_version}</span></td><td>{p.quantity}</td><td>{coins(p.average_acquisition_price)}</td><td>{p.current_lowest_bin?<><strong>{coins(p.current_lowest_bin)}</strong><span className="sourceMeta">{p.execution_mark_source||"execution observation"} · {age(p.execution_mark_age_seconds)} old · observation confidence {pct(p.execution_observation_confidence)}</span></>:<><strong className="noExecutableMark">No executable mark</strong><span className="sourceMeta">Need fresh execution observation; fair value is not substituted.</span></>}</td><td className={p.current_liquidation_profit_after_tax===null||p.current_liquidation_profit_after_tax===undefined?"muted":p.current_liquidation_profit_after_tax>=0?"positive":"negative"}>{coins(p.current_liquidation_profit_after_tax)}</td><td><strong>{coins(p.reference_price)}</strong><span className="sourceMeta">{p.reference_source||"reference"} · {age(p.reference_age_seconds)} old{p.reference_uncertainty_pct!==null&&p.reference_uncertainty_pct!==undefined?` · uncertainty ${pct(p.reference_uncertainty_pct)}`:""}</span></td><td><div style={{display:"flex",alignItems:"center"}}><input className="positionPriceInput" inputMode="numeric" placeholder="Set price" value={desired[p.position_id]||""} onChange={e=>setDesired(v=>({...v,[p.position_id]:e.target.value}))} onBlur={()=>saveDesired(p)}/><button className="button secondary inlineSave" disabled={saving===p.position_id} onClick={()=>saveDesired(p)}>{saving===p.position_id?"…":"Save"}</button></div></td><td className={projected===null?"muted":projected>=0?"positive":"negative"}>{coins(projected)}</td><td><ActionBadge action={p.current_action}/><span className="sourceMeta">Trade/model confidence {pct(p.trade_model_confidence)}</span></td><td><button className="button secondary" onClick={()=>beginSale(p)}>MARK SOLD / PARTIAL SALE</button></td></tr>})}</tbody></table></div>:<p className="muted">No open positions.</p>}</section>
 <div className="stack"><section className="panel"><div className="panelTitle"><h2>Set current coin balance</h2></div><div className="formRow"><input inputMode="numeric" value={balance} onChange={e=>setBalance(e.target.value)}/><button className="button secondary" onClick={saveBalance}>Save</button></div><p className="muted">Use this for initial setup or external coin changes. Purchases and sales update it automatically.</p></section>
 {salePos&&<section className="panel"><div className="panelTitle"><h2>MARK SOLD / PARTIAL SALE</h2><button className="button secondary" onClick={()=>setSalePos(null)}>Cancel</button></div><div className="notice">{salePos.card} · {salePos.quantity} owned at {coins(salePos.average_acquisition_price)} avg</div><div className="form" style={{marginTop:10}}><div className="formRow"><div className="field"><label>Quantity</label><input inputMode="numeric" value={saleQty} onChange={e=>setSaleQty(e.target.value)}/></div><div className="field"><label>Sale price each</label><input inputMode="numeric" value={salePrice} onChange={e=>setSalePrice(e.target.value)}/></div></div><p className="muted">Defaults to your desired listing price, then the latest executable mark. It never defaults to the reference/fair-value anchor.</p><button className="button" onClick={sell}>Record sale</button></div></section>}
 <section className="panel"><div className="panelTitle"><h2>MARK BOUGHT / ADD PURCHASE</h2></div><div className="form"><div className="formRow"><input placeholder="Search exact card" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();search()}}}/><button className="button secondary" onClick={search}>Search</button></div>{cards.length>0&&!selected&&<div className="searchResults">{cards.slice(0,8).map(c=><button className="searchItem" key={c.id} onClick={()=>setSelected(c)}><strong>{c.rating?`${c.rating} `:""}{c.name}</strong> <span className="muted">{c.version||""}</span></button>)}</div>}{selected&&<><div className="notice">Selected: {selected.rating?`${selected.rating} `:""}{selected.name} · {selected.version||""}</div><div className="formRow"><div className="field"><label>Quantity</label><input inputMode="numeric" value={qty} onChange={e=>setQty(e.target.value)}/></div><div className="field"><label>Buy price each</label><input inputMode="numeric" value={price} onChange={e=>setPrice(e.target.value)}/></div></div><button className="button" onClick={buy}>Record purchase</button></>}</div></section></div></div></>;
}
